# Generated by Django 3.2.5 on 2021-07-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='created_date',
            field=models.DateField(auto_now_add=True, db_column='created_date', null=True),
        ),
    ]
