# Generated by Django 3.2.5 on 2021-07-17 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userinfo_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='username',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='company_name',
            field=models.CharField(blank=True, db_column='company_name', max_length=200),
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, db_column='full_name', max_length=200)),
                ('phone_number', models.CharField(blank=True, db_column='phone_number', max_length=200)),
                ('username', models.CharField(blank=True, db_column='username', max_length=200)),
                ('password', models.CharField(blank=True, db_column='password', max_length=100)),
                ('is_admin', models.BooleanField(db_column='is_admin', default=False)),
                ('created_date', models.DateField(auto_now_add=True, db_column='created_date', null=True)),
                ('userinfo', models.ForeignKey(db_column='userinfo', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userinfo')),
            ],
        ),
    ]
