# Generated by Django 3.2.5 on 2021-08-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210717_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='usertype',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
