# Generated by Django 3.2.5 on 2021-08-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210809_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
