# Generated by Django 3.2.5 on 2021-08-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userinfo_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
