# Generated by Django 3.2.5 on 2021-07-05 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, db_column='company_name', max_length=100)),
                ('full_name', models.CharField(blank=True, db_column='full_name', max_length=200)),
                ('email_id', models.CharField(blank=True, db_column='email_id', max_length=200)),
                ('address', models.CharField(blank=True, db_column='address', max_length=200)),
                ('phone_number', models.CharField(blank=True, db_column='phone_number', max_length=200)),
                ('postal_code', models.CharField(blank=True, db_column='postal_code', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, db_column='year', max_length=100)),
                ('brand', models.CharField(blank=True, db_column='brand', max_length=200)),
                ('brand_model', models.CharField(blank=True, db_column='brand_model', max_length=200)),
                ('odo_meter', models.CharField(blank=True, db_column='odo_meter', max_length=200)),
                ('lic_plate', models.CharField(blank=True, db_column='lic_plate', max_length=200)),
                ('gvwr', models.CharField(blank=True, db_column='gvwr', max_length=200)),
                ('vin', models.CharField(blank=True, db_column='vin', max_length=200)),
                ('engine', models.CharField(blank=True, db_column='engine', max_length=200)),
                ('cylinder', models.CharField(blank=True, db_column='cylinder', max_length=200)),
                ('customer_id', models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_date', models.DateField(blank=True, db_column='selected_date')),
                ('vehicle_id', models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.vehicleinfo')),
            ],
        ),
    ]
