# Generated by Django 3.2.5 on 2021-07-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210707_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='address_2',
            field=models.CharField(blank=True, db_column='address_2', max_length=200),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='city',
            field=models.CharField(blank=True, db_column='city', max_length=200),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='state',
            field=models.CharField(blank=True, db_column='state', max_length=200),
        ),
    ]
