# Generated by Django 3.2.5 on 2021-07-17 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210717_1046'),
        ('customer', '0003_auto_20210714_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userinfo'),
        ),
    ]
