# Generated by Django 3.2.5 on 2021-07-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customerinfo_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinfo',
            name='engine_group',
            field=models.CharField(blank=True, db_column='engine_group', max_length=200),
        ),
    ]
