# Generated by Django 3.2.5 on 2021-08-24 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_termcondition'),
        ('customer', '0006_alter_vehicleinfo_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_text', models.CharField(blank=True, db_column='terms_text', max_length=1000, null=True)),
                ('customer', models.ForeignKey(db_column='customer', null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customerinfo')),
                ('term', models.ForeignKey(db_column='term', null=True, on_delete=django.db.models.deletion.PROTECT, to='service.termcondition')),
            ],
        ),
    ]
