# Generated by Django 3.2.5 on 2021-10-11 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_customerinfo_estimate_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmogTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smog', models.CharField(blank=True, db_column='smog', max_length=100)),
                ('type', models.CharField(blank=True, db_column='type', max_length=100)),
                ('desc', models.CharField(blank=True, db_column='desc', max_length=300)),
                ('vehicle_id', models.ForeignKey(db_column='vehicle_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.vehicleinfo')),
            ],
        ),
    ]
