# Generated by Django 3.2.5 on 2021-10-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_smogtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinfo',
            name='state',
            field=models.CharField(blank=True, db_column='state', max_length=100),
        ),
    ]
