# Generated by Django 3.2.5 on 2021-11-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20211011_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='status',
            field=models.CharField(blank=True, db_column='status', default='Active', max_length=100),
        ),
    ]
