# Generated by Django 3.2.5 on 2021-11-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_customerinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinfo',
            name='status',
            field=models.CharField(blank=True, db_column='status', default='Active', max_length=100),
        ),
    ]
