# Generated by Django 3.2.5 on 2021-11-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_customerinfo_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='signature',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
