# Generated by Django 3.2.5 on 2021-11-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_customerinfo_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinfo',
            name='deleted_form',
            field=models.CharField(blank=True, db_column='deleted_form', default='Active', max_length=100),
        ),
    ]
