# Generated by Django 3.2.5 on 2021-11-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_vehicleinfo_deleted_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinfo',
            name='vehicle_signature',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
