# Generated by Django 3.2.5 on 2022-08-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_vehicleinfo_vehicle_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='customer_id',
            field=models.CharField(blank=True, db_column='customer_id', max_length=20),
        ),
    ]
