# Generated by Django 3.2.5 on 2021-07-22 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0004_customerinfo_user_id'),
        ('service', '0002_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_amount', models.CharField(blank=True, db_column='final_amount', max_length=200)),
                ('tax_offered', models.CharField(blank=True, db_column='tax_offered', max_length=200)),
                ('discount_offered', models.CharField(blank=True, db_column='discount_offered', max_length=200)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('cancelled', 'cancelled')], db_column='status', max_length=10)),
                ('created_date', models.DateField(auto_now_add=True, db_column='created_date', null=True)),
                ('modified_date', models.DateField(auto_now_add=True, db_column='modified_date', null=True)),
                ('Vehicle', models.ForeignKey(db_column='Vehicle', null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.vehicleinfo')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, db_column='service_name', max_length=100)),
                ('amount', models.CharField(blank=True, db_column='amount', max_length=100)),
                ('Payment', models.ForeignKey(db_column='payment', null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.paymententry')),
                ('service_item', models.ForeignKey(db_column='service_item', null=True, on_delete=django.db.models.deletion.PROTECT, to='service.serviceslist')),
            ],
        ),
    ]
