# Generated by Django 3.2.5 on 2021-07-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Other', 'Other')], db_column='payment_mode', max_length=10),
        ),
    ]
