# Generated by Django 3.2.5 on 2021-07-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymententry_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='amount_tendered',
            field=models.CharField(blank=True, db_column='amount_tendered', max_length=200),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='changed_given',
            field=models.CharField(blank=True, db_column='changed_given', max_length=200),
        ),
    ]
