# Generated by Django 3.2.5 on 2021-07-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20210726_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='amount',
            field=models.FloatField(blank=True, db_column='amount', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymententry',
            name='amount_tendered',
            field=models.FloatField(blank=True, db_column='amount_tendered', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymententry',
            name='changed_given',
            field=models.FloatField(blank=True, db_column='changed_given', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymententry',
            name='discount_offered',
            field=models.FloatField(blank=True, db_column='discount_offered', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymententry',
            name='final_amount',
            field=models.FloatField(blank=True, db_column='final_amount', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymententry',
            name='tax_offered',
            field=models.FloatField(blank=True, db_column='tax_offered', max_length=200, null=True),
        ),
    ]
