# Generated by Django 3.2.5 on 2021-07-28 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_serviceslist_amount'),
        ('payment', '0005_discountitem_feesitem_taxitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountitem',
            name='discount_item',
            field=models.ForeignKey(db_column='discount_item', null=True, on_delete=django.db.models.deletion.PROTECT, to='service.discounts'),
        ),
        migrations.AlterField(
            model_name='discountitem',
            name='discount_name',
            field=models.CharField(blank=True, db_column='discount_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='feesitem',
            name='fees_item',
            field=models.ForeignKey(db_column='fees_item', null=True, on_delete=django.db.models.deletion.PROTECT, to='service.fees'),
        ),
        migrations.AlterField(
            model_name='feesitem',
            name='fees_name',
            field=models.CharField(blank=True, db_column='fees_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='taxitem',
            name='tax_item',
            field=models.ForeignKey(db_column='tax_item', null=True, on_delete=django.db.models.deletion.PROTECT, to='service.taxes'),
        ),
        migrations.AlterField(
            model_name='taxitem',
            name='tax_name',
            field=models.CharField(blank=True, db_column='tax_name', max_length=100),
        ),
    ]
