# Generated by Django 3.2.5 on 2021-07-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20210728_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='additional_comments',
            field=models.CharField(blank=True, db_column='additional_comments', max_length=200),
        ),
    ]
