# Generated by Django 3.2.5 on 2021-07-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_musthave_testtype'),
        ('payment', '0007_paymententry_additional_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountitem',
            old_name='discount_name',
            new_name='offer_name',
        ),
        migrations.CreateModel(
            name='TestTypeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type_name', models.CharField(blank=True, db_column='test_type_name', max_length=100)),
                ('Payment', models.ForeignKey(db_column='payment', null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.paymententry')),
                ('test_item', models.ForeignKey(db_column='test_item', null=True, on_delete=django.db.models.deletion.PROTECT, to='service.testtype')),
            ],
        ),
        migrations.CreateModel(
            name='MustHaveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_have_name', models.CharField(blank=True, db_column='must_have_name', max_length=100)),
                ('Payment', models.ForeignKey(db_column='payment', null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.paymententry')),
                ('must_have_item', models.ForeignKey(db_column='must_have_item', null=True, on_delete=django.db.models.deletion.PROTECT, to='service.musthave')),
            ],
        ),
    ]
