# Generated by Django 3.2.5 on 2021-08-05 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210717_1046'),
        ('payment', '0008_auto_20210729_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquareDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, db_column='device', max_length=100)),
                ('name', models.CharField(blank=True, db_column='name_device', max_length=100)),
                ('code', models.CharField(blank=True, db_column='code', max_length=100)),
                ('location', models.CharField(blank=True, db_column='location', max_length=100)),
                ('status', models.CharField(blank=True, db_column='status', max_length=100)),
                ('client', models.ForeignKey(db_column='client', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userinfo')),
            ],
        ),
    ]
