# Generated by Django 3.2.5 on 2021-08-05 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210717_1046'),
        ('payment', '0009_squaredevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='squaredevice',
            name='square_id',
            field=models.CharField(blank=True, db_column='square_id', max_length=100),
        ),
        migrations.AlterField(
            model_name='squaredevice',
            name='device_id',
            field=models.CharField(blank=True, db_column='device_id', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SquareTerminalCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_id', models.CharField(blank=True, db_column='checkout_id', max_length=200)),
                ('client', models.ForeignKey(db_column='client', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userinfo')),
            ],
        ),
    ]
