# Generated by Django 3.2.5 on 2021-08-06 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20210805_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='squareterminalcheckout',
            name='payment',
            field=models.ForeignKey(db_column='Payment', null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.paymententry'),
        ),
    ]
