# Generated by Django 3.2.5 on 2021-08-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_squareterminalcheckout_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='invoice_id',
            field=models.CharField(blank=True, db_column='invoice', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymententry',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='created_date', null=True),
        ),
        migrations.AlterField(
            model_name='paymententry',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, db_column='modified_date', null=True),
        ),
    ]
