# Generated by Django 3.2.5 on 2021-09-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20210807_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='card_amount',
            field=models.FloatField(blank=True, db_column='card_amount', max_length=200, null=True),
        ),
    ]
