# Generated by Django 3.2.5 on 2021-09-07 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usertype_image_name'),
        ('payment', '0013_paymententry_card_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortisPayCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_column='username', max_length=100)),
                ('password', models.CharField(blank=True, db_column='password', max_length=100)),
                ('domain', models.CharField(blank=True, db_column='domain', max_length=100)),
                ('client', models.ForeignKey(db_column='client', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userinfo')),
            ],
        ),
    ]
