# Generated by Django 3.2.5 on 2021-10-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_auto_20210921_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountitem',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='created_date', null=True),
        ),
        migrations.AddField(
            model_name='feesitem',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='created_date', null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='created_date', null=True),
        ),
        migrations.AddField(
            model_name='taxitem',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='created_date', null=True),
        ),
    ]
