# Generated by Django 3.2.5 on 2021-10-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_auto_20211007_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='inception_declined',
            field=models.BooleanField(db_column='inception_declined', default=False),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='inception_performed',
            field=models.BooleanField(db_column='inception_performed', default=False),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='initials',
            field=models.CharField(blank=True, db_column='Initials', max_length=30),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='lf',
            field=models.CharField(blank=True, db_column='LF', max_length=30),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='lr',
            field=models.CharField(blank=True, db_column='LR', max_length=30),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='reasons',
            field=models.CharField(blank=True, db_column='Reasons', max_length=30),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='rf',
            field=models.CharField(blank=True, db_column='RF', max_length=30),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='rr',
            field=models.CharField(blank=True, db_column='RR', max_length=30),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='test_results',
            field=models.CharField(blank=True, db_column='Test_Results', max_length=30),
        ),
    ]
