# Generated by Django 3.2.5 on 2021-10-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_auto_20211008_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='fly_discount',
            field=models.FloatField(db_column='fly_discount', default=0),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='fly_fees',
            field=models.FloatField(db_column='fly_fees', default=0),
        ),
    ]
