# Generated by Django 3.2.5 on 2021-10-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_auto_20211011_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='transaction_id',
            field=models.CharField(blank=True, db_column='transaction_id', max_length=100),
        ),
    ]
