# Generated by Django 3.2.5 on 2021-07-17 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20210717_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_value', models.CharField(blank=True, db_column='tax_value', max_length=20)),
                ('client', models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, db_column='service_name', max_length=200)),
                ('input_mode', models.CharField(blank=True, db_column='input_mode', max_length=200)),
                ('amount', models.CharField(blank=True, db_column='amount', max_length=30)),
                ('client', models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, db_column='company_name', max_length=200)),
                ('address', models.CharField(blank=True, db_column='address', max_length=200)),
                ('phone_number', models.CharField(blank=True, db_column='phone_number', max_length=200)),
                ('website_url', models.CharField(blank=True, db_column='website_url', max_length=200)),
                ('footer_note', models.CharField(blank=True, db_column='footer_note', max_length=200)),
                ('client', models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_value', models.CharField(blank=True, db_column='discount_value', max_length=20)),
                ('offer_name', models.CharField(blank=True, db_column='offer_name', max_length=50)),
                ('client', models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userinfo')),
            ],
        ),
    ]
