# Generated by Django 3.2.5 on 2021-07-19 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210717_1046'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Default',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, db_column='currency', max_length=200)),
                ('langaugge', models.CharField(blank=True, db_column='langaugge', max_length=200)),
                ('time_zone', models.CharField(blank=True, db_column='time_zone', max_length=400)),
                ('display_time', models.CharField(blank=True, db_column='display_time', max_length=200)),
                ('date_format', models.CharField(blank=True, db_column='date_format', max_length=200)),
                ('client', models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userinfo')),
            ],
        ),
    ]
