# Generated by Django 3.2.5 on 2021-07-26 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210717_1046'),
        ('service', '0002_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxes',
            name='tax_name',
            field=models.CharField(blank=True, db_column='tax_name', max_length=200),
        ),
        migrations.AddField(
            model_name='taxes',
            name='visible',
            field=models.BooleanField(db_column='visible', default=False),
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_value', models.CharField(blank=True, db_column='fees_value', max_length=20)),
                ('fees_name', models.CharField(blank=True, db_column='fees_name', max_length=200)),
                ('visible', models.BooleanField(db_column='visible', default=False)),
                ('client', models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userinfo')),
            ],
        ),
    ]
