# Generated by Django 3.2.5 on 2021-07-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210726_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceslist',
            name='amount',
            field=models.FloatField(blank=True, db_column='amount', max_length=30, null=True),
        ),
    ]
