# Generated by Django 3.2.5 on 2021-08-02 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210717_1046'),
        ('service', '0005_musthave_testtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_discount_amount', models.CharField(blank=True, db_column='cash_discount_amount', max_length=200)),
                ('visible', models.BooleanField(db_column='visible', default=False)),
                ('client', models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userinfo')),
            ],
        ),
    ]
