# Generated by Django 3.2.5 on 2021-08-05 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210717_1046'),
        ('service', '0006_cashdiscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquareCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(blank=True, db_column='application_id', max_length=100)),
                ('application_secret', models.CharField(blank=True, db_column='application_secret', max_length=100)),
                ('location_id', models.CharField(blank=True, db_column='location_id', max_length=100)),
                ('accees_token', models.CharField(blank=True, db_column='accees_token', max_length=100)),
                ('client', models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userinfo')),
            ],
        ),
    ]
