# Generated by Django 3.2.5 on 2021-08-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20210812_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptcontent',
            name='image_name',
            field=models.CharField(blank=True, db_column='image_name', max_length=300),
        ),
    ]
