# Generated by Django 3.2.5 on 2021-08-24 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usertype_image_name'),
        ('service', '0009_receiptcontent_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_text', models.CharField(blank=True, db_column='term_text', max_length=200)),
                ('visible', models.BooleanField(db_column='visible', default=False)),
                ('client', models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userinfo')),
            ],
        ),
    ]
