# Generated by Django 3.2.5 on 2021-08-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_termcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='default',
            name='print_format',
            field=models.CharField(blank=True, db_column='Print_format', max_length=50),
        ),
    ]
