# Generated by Django 3.2.5 on 2021-08-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_default_print_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termcondition',
            name='term_text',
            field=models.CharField(blank=True, db_column='term_text', max_length=2000),
        ),
    ]
