# Generated by Django 3.2.5 on 2021-09-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_termcondition_term_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='default',
            name='payment_gatway',
            field=models.CharField(blank=True, db_column='payment_gatway', max_length=100),
        ),
    ]
