# Generated by Django 3.2.5 on 2021-10-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_serviceslist_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxes',
            name='tax_value',
            field=models.CharField(blank=True, db_column='tax_value', max_length=20, null=True),
        ),
    ]
